add footer html and css
MihailShev/Ctrl-Alt-Elite pull request #1
Opened 2024-10-17 12:16 UTC by YliiaRom

Для підключення меню потрібні id-родзділів: 
how it works
vegetables
reviews

Для семантичності краще окремим тегом adress . Зробіть окремо а і address чи помістіть їх у спісок?-зробила окремо- семантично різній вміст.

Privacy Policy
Cookie settings- це ссилки- яку адресу вказати, чи просто #?

Посиланням зміну кольору треба робити при ховері та фокусі, чі відслідковувати стан activ?

!похибка- забула видалити ..перед адресою сайта. Буду правити з іншими настановами.

2024-10-17 12:47 UTC, MihailShev commented on src/css/footer.css
> +  font-family: "Inter Tight", sans-serif;
font-family задан по умолчанию для тега body и все его элементы по наследству получают этот шрифт, поэтому можно указывать только жирность

2024-10-17 12:57 UTC, YliiaRom commented on src/css/footer.css
> +  font-family: "Inter Tight", sans-serif;
удалю.

2024-10-17 13:48 UTC, MihailShev requested changes

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +.footer-container {
используй класс container он прописан в файле container.css

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +.footer-body {
убери от сюда текстовые свойства и пропиши их для параграфа который в этом диве, так будет легче продолжать поддерживать сайт в будущем

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +  line-height: 18px;
line-height: 1.28571; по макету округляем до 1.3 и там можно не прописывать "px"

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +.tablet-logo {
display: none; тут достаточно одного этого свойства,  а эти можешь убрать
"  visibility: hidden;
  opacity: 0;
  pointer-events: none;"

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +  letter-spacing: -0.42px;
по макету letter-spacing: -0.01em;

2024-10-17 13:48 UTC, MihailShev commented on src/partials/footer.html
> +          <ul class="footer-menu-list">
оберните тег `<ul class="footer-menu-list"> в тег <nav> `так лучше для доступности

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +.footer-contacts {
убери от сюда текстовые свойства и задай для `ссылки с классом=footer-contacts-link и параграфу с классом=footer-address`

2024-10-17 13:48 UTC, MihailShev commented on src/partials/footer.html
> +
`в теге  <address class="footer-address"> у тебя должно быть  <a class="footer-contacts-link"> и <p>с текстом 1678 S. Pioneer Road Salt Lake City UT 84104`

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +  letter-spacing: -0.21px;
letter-spacing: -0.01em; по макету

2024-10-17 13:48 UTC, MihailShev commented on src/partials/footer.html
> +            &#169;Green Harvest 2023
Green Harvest 2023 возьми этот текст в `<p>`

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +    font-size: 16px;
font-family: "Inter Tight";лишнее он по наследству от body

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +letter-spacing: -0.27px;
letter-spacing: -0.27px; не по макету

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +letter-spacing: -0.27px;
letter-spacing: -0.27px;не по макету

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +letter-spacing: -0.27px;
letter-spacing: -0.27px;не по макету

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> +    letter-spacing: -0.48px;
letter-spacing: -0.48px;не по макету

2024-10-17 13:48 UTC, MihailShev commented on src/css/footer.css
> + visibility: visible;
display: block; достаточно только этого

2024-10-17 15:24 UTC, YliiaRom commented on src/css/footer.css
> +.footer-container {
приняла

2024-10-19 03:35 UTC, YliiaRom commented on src/css/footer.css
> + visibility: visible;
добрый день. Всё готово) жду проверки когда будет удобно. Хорошего дня.

2024-10-19 07:35 UTC, MihailShev requested changes
Все отлично, просто по удаляй закомментированые свойства

2024-10-19 07:35 UTC, MihailShev commented on src/css/footer.css
> +} */
`/* .container {
  max-width: 355px;
  padding: 0 10px;
  margin: 0 auto;
} */` удали закоментированый код

2024-10-19 07:35 UTC, MihailShev commented on src/css/footer.css
> +.footer-text-container p {
этот див можно удалить и он не повлияет на геометрию футера, только дайте класс параграфу который внутри этого дива и перенесите туда шрифтовые стили

2024-10-19 07:35 UTC, MihailShev commented on src/css/footer.css
> +address {
лучше дать тегу класс и обратиться по нему

2024-10-19 07:35 UTC, MihailShev commented on src/partials/footer.html
> +                <p class="footer-address">
прошу простить в прошлый раз сказал сделать параграфом, а когда погуглил оказалось что такое место есть и я сделал ссылкой

2024-10-19 08:16 UTC, YliiaRom commented on src/css/footer.css
> +} */
+

2024-10-19 08:30 UTC, YliiaRom commented on src/css/footer.css
> +.footer-text-container p {
+

2024-10-19 08:32 UTC, YliiaRom commented on src/css/footer.css
> +address {
+

2024-10-19 08:47 UTC, YliiaRom commented on src/partials/footer.html
> +                <p class="footer-address">
Михаил, ну ты крутой! я в шоке от тчательности проверки. Если что всегда готова исправить ;), держись тебе работы больше всех досталось.
Висхищаюсь Вашей ответственностью! телефончик сохраню, если после окончания курса будут вопросы, я теперь знаю очень компетентного Вас )

2024-10-19 09:26 UTC, YliiaRom commented on src/partials/footer.html
> +                <p class="footer-address">
проверьте пожалуйста

2024-10-19 10:00 UTC, MihailShev approved these changes
Отлично поработали спасибо за труд и за теплые слова)

2024-10-19 10:00 UTC, merged