Created section hero
MihailShev/Ctrl-Alt-Elite pull request #11
Opened 2024-10-20 10:26 UTC by Nik-gurulov528

2024-10-20 11:54 UTC, MihailShev requested changes

2024-10-20 11:54 UTC, MihailShev commented on src/css/hero.css
font-family: 'Inter Tight', sans-serif; это по наследству от body можешь удалить его везде потому что на сайте только один шрифт

2024-10-20 11:54 UTC, MihailShev commented on src/css/hero.css
> +  margin: 0;
`margin: 0;` уже скинуто в файле `reset.css`

2024-10-20 11:54 UTC, MihailShev commented on src/css/hero.css
> +  padding-bottom: 20px;
лучше `margin-bottom: 20px`

2024-10-20 11:54 UTC, MihailShev commented on src/css/hero.css
> +    padding-bottom: 25px;
лучше `margin-bottom: 20px`

2024-10-20 11:54 UTC, MihailShev commented on src/css/hero.css
> +    padding-bottom: 128px;
лучше` margin-bottom: 128px`

2024-10-20 16:51 UTC, Nik-gurulov528 commented on src/css/hero.css
> +    padding-bottom: 128px;
Все виправив

2024-10-20 18:52 UTC, MihailShev requested changes

2024-10-20 18:52 UTC, MihailShev commented on src/css/hero.css
> +  background-color: #576f35;
перед правилом `.hero-container` пропиши правило
 `.hero{
background-color: #576f35;
}`
а здесь `.hero-container` удали `background-color: #576f35;`

2024-10-21 07:02 UTC, MihailShev approved these changes

2024-10-21 07:02 UTC, merged